hunter_config(Boost VERSION 1.72.0-p1)
hunter_config(cxxopts VERSION 2.2.0)
hunter_config(Eigen VERSION 3.3.9)
hunter_config(fmt VERSION 7.1.2)
hunter_config(GTest VERSION 1.10.0-p1)
hunter_config(nlohmann_json VERSION 3.8.0)
hunter_config(spdlog VERSION 1.8.0-p1)
